[tool.poetry]
name = "pytezos"
version = "1.1.1"
description = "Python utils for Tezos"
authors = ["Arthur Breitman, Michael Zaikin <baking-bad.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/baking-bad/pytezos"
keywords = ['tezos', 'crypto', 'blockchain', 'xtz']

[tool.poetry.dependencies]
python = "^3.5"
pysodium = "^0.7.1"
pyblake2 = "^1.1.2"
base58 = "^1.0.3"
secp256k1 = "^0.13.2"
requests = "^2.21.0"
pendulum = "*"
fastecdsa = "^1.7.1"
loguru = "*"
netstruct = "*"
tqdm = "*"
ply = "*"
simplejson = "*"

[tool.poetry.dev-dependencies]
parameterized = "^0.7.0"
pytest = "^3.0"
pytest-cov = "^2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
